---
ID: "451f99a1-4fd1-4fc5-8497-b2ebe8369960"
Parent: "b0cc9343-5e87-454d-aa26-2685f29061a2"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/TE Connectivity/TE Connectivity/Presentation/Headless Variants/MegaTrends/Default"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T000000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
