---
ID: "580ea79d-3daf-4ed7-8722-b3e952cfe653"
Parent: "ba417bb7-a5ac-41fd-af11-f2692026e0f2"
Template: "ba417bb7-a5ac-41fd-af11-f2692026e0f2"
Path: "/sitecore/templates/Project/nxp/Page Design Folder/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260324T000000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "678f973d-1b67-4e2b-8a7d-dc4ed8b9c070"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260324T000000Z
