---
ID: "d9c5b901-a906-4645-8e36-4d8ac172a160"
Parent: "f7a02d0e-60ea-4cc6-bc78-85234f1ebbdf"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: "/sitecore/content/TE Connectivity/TE Connectivity/Presentation/Placeholder Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - Hint: TemplateForCreation
      Value: "{D2A6884C-04D5-4089-A64E-D27CA9D68D4C}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T000000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
