import { db } from "./db";
import { categories, products, priceBreaks, users } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const [existingProducts] = await db.select({ count: sql<number>`count(*)::int` }).from(products);
  if (existingProducts.count > 0) return;

  const [demoUser] = await db.insert(users).values({
    username: "demo",
    password: "demo123",
    companyName: "Acme Electronics Inc.",
    firstName: "John",
    lastName: "Mitchell",
    email: "john.mitchell@acmeelectronics.com",
    role: "buyer",
  }).returning();

  const cats = await db.insert(categories).values([
    { name: "Connectors", slug: "connectors", description: "High-reliability connectors for industrial, automotive, and aerospace applications", sortOrder: 1 },
    { name: "Sensors", slug: "sensors", description: "Precision sensors for temperature, pressure, position, and vibration measurement", sortOrder: 2 },
    { name: "Relays", slug: "relays", description: "Electromechanical and solid-state relays for switching and control circuits", sortOrder: 3 },
    { name: "Wire & Cable", slug: "wire-cable", description: "High-performance wire, cable, and cable assemblies for signal and power applications", sortOrder: 4 },
    { name: "Circuit Protection", slug: "circuit-protection", description: "Fuses, TVS diodes, and resettable devices for circuit safety", sortOrder: 5 },
    { name: "Terminal Blocks", slug: "terminal-blocks", description: "PCB and DIN rail terminal blocks for secure wiring connections", sortOrder: 6 },
  ]).returning();

  const catMap: Record<string, string> = {};
  cats.forEach(c => { catMap[c.slug] = c.id; });

  const prods = await db.insert(products).values([
    {
      name: "DEUTSCH DT 12-Pin Connector Assembly",
      sku: "DT06-12S-CE06",
      description: "Rugged environmentally sealed connector system for automotive and industrial applications. Features thermoplastic housing with integrated rear wire seal and secondary locking wedge.",
      categoryId: catMap["connectors"],
      basePrice: "24.5000",
      imageUrl: "/images/connector-dt12.svg",
      specs: { "Pin Count": "12", "Wire Range": "20-16 AWG", "Current Rating": "13A per contact", "Voltage Rating": "75V DC", "IP Rating": "IP67/IP69K", "Operating Temp": "-55C to +125C", "Housing Material": "Nylon 6/6", "Contact Plating": "Nickel w/ Gold Flash" },
      industry: "Automotive",
      application: "Engine Harness",
      minOrderQty: 10,
      leadTimeDays: 3,
      inStock: true,
      stockQty: 2500,
    },
    {
      name: "M12 Circular Connector 8-Pos D-Coded",
      sku: "T4171110008-001",
      description: "M12 D-coded circular connector for Industrial Ethernet applications, supporting Cat 5e performance with EMI shielded housing.",
      categoryId: catMap["connectors"],
      basePrice: "18.7500",
      imageUrl: "/images/connector-m12.svg",
      specs: { "Pin Count": "8", "Coding": "D-Coded", "Data Rate": "100 Mbps", "IP Rating": "IP67", "Operating Temp": "-40C to +85C", "Cable OD": "4-8mm", "Mounting": "Panel Mount" },
      industry: "Industrial Automation",
      application: "Ethernet Communication",
      minOrderQty: 5,
      leadTimeDays: 5,
      inStock: true,
      stockQty: 800,
    },
    {
      name: "AMPSEAL 16 Series 23-Pin Plug",
      sku: "776087-1",
      description: "Automotive-grade sealed connector designed for high-vibration underhood environments. Compatible with automatic wire termination for high-volume production.",
      categoryId: catMap["connectors"],
      basePrice: "32.2000",
      imageUrl: "/images/connector-ampseal.svg",
      specs: { "Pin Count": "23", "Wire Range": "22-16 AWG", "Current Rating": "17.5A", "Voltage Rating": "400V AC", "IP Rating": "IP6K9K", "Operating Temp": "-40C to +150C", "Mating Cycles": "25 minimum" },
      industry: "Automotive",
      application: "Powertrain Systems",
      minOrderQty: 25,
      leadTimeDays: 7,
      inStock: true,
      stockQty: 1200,
    },
    {
      name: "RTD Pt100 Temperature Sensor Assembly",
      sku: "NB-PTCO-152",
      description: "Class A platinum resistance temperature detector with stainless steel sheath and spring-loaded bayonet fitting for HVAC and process control.",
      categoryId: catMap["sensors"],
      basePrice: "45.8000",
      imageUrl: "/images/sensor-rtd.svg",
      specs: { "Type": "Pt100 RTD", "Accuracy": "Class A (IEC 60751)", "Temp Range": "-50C to +500C", "Sheath Material": "316 SS", "Sheath Diameter": "6mm", "Lead Wires": "3-wire", "Response Time": "< 5 sec" },
      industry: "Industrial Automation",
      application: "Process Control",
      minOrderQty: 1,
      leadTimeDays: 10,
      inStock: true,
      stockQty: 350,
    },
    {
      name: "Piezoelectric Vibration Sensor 100mV/g",
      sku: "805M1-0100",
      description: "Industrial accelerometer with ceramic sensing element for predictive maintenance and machine condition monitoring applications.",
      categoryId: catMap["sensors"],
      basePrice: "128.5000",
      imageUrl: "/images/sensor-piezo.svg",
      specs: { "Sensitivity": "100 mV/g", "Frequency Range": "2-10,000 Hz", "Dynamic Range": "80g peak", "Operating Temp": "-40C to +121C", "Output": "2-wire IEPE", "Mounting": "1/4-28 UNF stud", "Weight": "50g" },
      industry: "Industrial Automation",
      application: "Condition Monitoring",
      minOrderQty: 1,
      leadTimeDays: 14,
      inStock: true,
      stockQty: 120,
    },
    {
      name: "Pressure Transducer 0-100 PSI 4-20mA",
      sku: "U5374-000005-100PG",
      description: "Stainless steel media-isolated pressure transducer with 4-20mA analog output for hydraulic and pneumatic pressure measurement.",
      categoryId: catMap["sensors"],
      basePrice: "89.0000",
      imageUrl: "/images/sensor-pressure.svg",
      specs: { "Range": "0-100 PSI", "Output": "4-20mA", "Accuracy": "0.25% FSO (BFSL)", "Burst Pressure": "3x rated", "Media": "Fluids & gases", "Connection": "1/4 NPT Male", "Supply Voltage": "10-30 VDC" },
      industry: "Industrial Automation",
      application: "Hydraulic Systems",
      minOrderQty: 1,
      leadTimeDays: 7,
      inStock: true,
      stockQty: 200,
    },
    {
      name: "PCB Power Relay 30A SPST-NO",
      sku: "T9AS1D12-12",
      description: "High-current PCB relay with flange mount for HVAC controls, power supplies, and industrial switching. UL/cUL recognized.",
      categoryId: catMap["relays"],
      basePrice: "6.2500",
      imageUrl: "/images/relay-pcb.svg",
      specs: { "Contact Config": "SPST-NO", "Contact Rating": "30A @ 240VAC", "Coil Voltage": "12 VDC", "Coil Power": "1.6W", "Dielectric Strength": "2500 VAC", "Insulation": "Class F", "Life": "100,000 ops" },
      industry: "Industrial Automation",
      application: "HVAC Control",
      minOrderQty: 50,
      leadTimeDays: 3,
      inStock: true,
      stockQty: 5000,
    },
    {
      name: "Contactor Relay 4-Pole 10A DIN Rail",
      sku: "ICS-V16A-4C-24",
      description: "Compact 4-pole contactor relay designed for DIN rail mounting in motor control and lighting circuits. EN 61095 compliant.",
      categoryId: catMap["relays"],
      basePrice: "22.4000",
      imageUrl: "/images/relay-contactor.svg",
      specs: { "Poles": "4 (2NO + 2NC)", "Contact Rating": "10A @ 250VAC", "Coil Voltage": "24 VAC/DC", "Mounting": "DIN Rail (35mm)", "Width": "45mm", "Operating Temp": "-25C to +50C", "Mechanical Life": "10M ops" },
      industry: "Industrial Automation",
      application: "Motor Control",
      minOrderQty: 10,
      leadTimeDays: 5,
      inStock: true,
      stockQty: 650,
    },
    {
      name: "Shielded Cat6A Ethernet Patch Cable 10ft",
      sku: "CAT6A-S-10-BL",
      description: "26 AWG stranded copper patch cable with RJ45 connectors, S/FTP shielding, and LSZH jacket for data center and industrial network installations.",
      categoryId: catMap["wire-cable"],
      basePrice: "12.9500",
      imageUrl: "/images/cable-cat6a.svg",
      specs: { "Category": "Cat 6A", "Length": "10 ft (3m)", "Conductor": "26 AWG stranded", "Shielding": "S/FTP (screened)", "Jacket": "LSZH", "Performance": "500 MHz / 10 Gbps", "Color": "Blue" },
      industry: "Data Communications",
      application: "Network Infrastructure",
      minOrderQty: 10,
      leadTimeDays: 2,
      inStock: true,
      stockQty: 3000,
    },
    {
      name: "Silicone Multi-Conductor Cable 18AWG 4C",
      sku: "SIL-18-4C-300V",
      description: "Flexible silicone rubber insulated multi-conductor cable rated for continuous high-temperature service in harsh environments.",
      categoryId: catMap["wire-cable"],
      basePrice: "3.7500",
      imageUrl: "/images/cable-silicone.svg",
      specs: { "Gauge": "18 AWG", "Conductors": "4", "Voltage Rating": "300V", "Insulation": "Silicone Rubber", "Temp Rating": "-60C to +200C", "UL Rating": "UL 3239", "Price Unit": "Per foot" },
      industry: "Industrial Automation",
      application: "High-Temp Wiring",
      minOrderQty: 100,
      leadTimeDays: 5,
      inStock: true,
      stockQty: 10000,
    },
    {
      name: "Automotive Blade Fuse 15A (Pack of 100)",
      sku: "FBF-15A-100PK",
      description: "Standard-size automotive blade fuses with zinc alloy element and transparent housing for visual blow indication.",
      categoryId: catMap["circuit-protection"],
      basePrice: "18.5000",
      imageUrl: "/images/fuse-blade.svg",
      specs: { "Rating": "15A @ 32V DC", "Type": "Standard blade (ATO)", "Element": "Zinc alloy", "Housing": "Polypropylene", "Interrupt Rating": "1000A", "Compliance": "SAE J1284", "Pack Qty": "100" },
      industry: "Automotive",
      application: "Electrical Distribution",
      minOrderQty: 1,
      leadTimeDays: 2,
      inStock: true,
      stockQty: 500,
    },
    {
      name: "TVS Diode Array USB 3.0 Protection",
      sku: "SESD0402Q2UG-0024-098",
      description: "Low-capacitance bidirectional TVS diode array designed to protect USB 3.0 data lines from ESD and lightning-induced transients.",
      categoryId: catMap["circuit-protection"],
      basePrice: "0.4500",
      imageUrl: "/images/tvs-diode.svg",
      specs: { "Working Voltage": "5V", "Clamping Voltage": "9.8V @ 1A", "Capacitance": "0.25 pF", "ESD Rating": "15 kV (contact)", "Package": "0402 DFN", "Channels": "2", "Application": "USB 3.0" },
      industry: "Consumer Electronics",
      application: "ESD Protection",
      minOrderQty: 500,
      leadTimeDays: 10,
      inStock: true,
      stockQty: 25000,
    },
    {
      name: "PCB Screw Terminal Block 5.0mm 12-Pos",
      sku: "OSTB-1200503",
      description: "Through-hole PCB terminal block with rising clamp wire entry for reliable field wiring in industrial control boards.",
      categoryId: catMap["terminal-blocks"],
      basePrice: "4.2500",
      imageUrl: "/images/terminal-block-pcb.svg",
      specs: { "Positions": "12", "Pitch": "5.0mm", "Wire Range": "28-12 AWG", "Current Rating": "15A", "Voltage Rating": "300V", "Mounting": "Through-hole", "Wire Entry": "Rising clamp" },
      industry: "Industrial Automation",
      application: "PCB Interconnect",
      minOrderQty: 25,
      leadTimeDays: 3,
      inStock: true,
      stockQty: 2000,
    },
    {
      name: "DIN Rail Terminal Block 10mm2 Feed-Through",
      sku: "XBUT10-FT-BG",
      description: "Spring-cage feed-through terminal block for 35mm DIN rail, with tool-free wiring and test point access for industrial panels.",
      categoryId: catMap["terminal-blocks"],
      basePrice: "3.8500",
      imageUrl: "/images/terminal-block-din.svg",
      specs: { "Cross Section": "10 mm2 (8 AWG)", "Current Rating": "57A", "Voltage Rating": "800V", "Connection": "Spring cage", "Mounting": "35mm DIN rail", "Width": "10.2mm", "Compliance": "IEC 60947-7-1" },
      industry: "Industrial Automation",
      application: "Panel Wiring",
      minOrderQty: 10,
      leadTimeDays: 3,
      inStock: true,
      stockQty: 3500,
    },
  ]).returning();

  for (const prod of prods) {
    const base = parseFloat(prod.basePrice);
    await db.insert(priceBreaks).values([
      { productId: prod.id, minQty: 1, price: base.toFixed(4) },
      { productId: prod.id, minQty: 25, price: (base * 0.95).toFixed(4) },
      { productId: prod.id, minQty: 100, price: (base * 0.88).toFixed(4) },
      { productId: prod.id, minQty: 500, price: (base * 0.80).toFixed(4) },
      { productId: prod.id, minQty: 1000, price: (base * 0.72).toFixed(4) },
    ]);
  }

  console.log("Database seeded successfully with TE.com-style product data");
}
