---
ID: "b77e350f-1faa-41f0-8dff-e64b6925ca93"
Parent: "18acdcc3-da0c-4587-8453-d6695a8e6ca4"
Template: "18acdcc3-da0c-4587-8453-d6695a8e6ca4"
Path: "/sitecore/templates/Project/NovaTechCollection/Components/PricingTable/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "f373ce49-3745-4f9a-8860-c2a5cf5cb818"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260301T000000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d2927e74-d9d0-4231-9799-d7565ea1f9a7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260301T000000Z
