// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useEffect } from 'react';
import React from 'react';
import { Text, RichText, Image, Link, AppPlaceholder, useSitecore, CdpHelper } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image },
      { name: 'Link', value: Link },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'useSitecore', value: useSitecore },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
