// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Text, RichText, Image, AppPlaceholder, Link } from '@sitecore-content-sdk/nextjs';
import React from 'react';
import componentMap from '.sitecore/component-map';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'Link', value: Link },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
