---
ID: "ca038bfc-3afe-4ac6-991b-07cd8b2d0376"
Parent: "49b0ab96-10ee-425f-992e-06967ff2c60d"
Template: "49b0ab96-10ee-425f-992e-06967ff2c60d"
Path: "/sitecore/templates/Project/NovaTechCollection/Components/ProductFeature/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6ac6ab7f-c94a-4853-903e-221c92e1a545"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260301T000000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63094540-49d3-40e8-8a1d-e328a5f79a89"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260301T000000Z
